import {
  canonicalJson,
  grade4Semester1Diagnosis,
  grade4Semester1DistractorRationales,
  grade4Semester1MisconceptionTitles,
  inspectDiagnosticIntegrity
} from "../packages/content/src/index";

interface SeededTeacherNote {
  set_key: string;
  version: string;
  judgment_id: string;
  choice_id: string;
  signal_ids: string[];
  misconception_key: string;
  misconception_title: string;
  teacher_note: string;
}

function sqlJson(value: unknown, tag: string): string {
  const serialized = canonicalJson(value);
  if (serialized.includes(`$${tag}$`)) {
    throw new Error(`SQL dollar quote tag collision: ${tag}`);
  }
  return `$${tag}$${serialized}$${tag}$::jsonb`;
}

function buildTeacherNotes(): SeededTeacherNote[] {
  return grade4Semester1DistractorRationales.map((item) => {
    const misconceptionTitle =
      grade4Semester1MisconceptionTitles[item.misconceptionId];
    if (!misconceptionTitle) {
      throw new Error(`Missing misconception title: ${item.misconceptionId}`);
    }
    return {
      set_key: grade4Semester1Diagnosis.manifest.id,
      version: grade4Semester1Diagnosis.manifest.version,
      judgment_id: item.judgmentId,
      choice_id: item.choiceId,
      signal_ids: [...item.signalIds],
      misconception_key: item.misconceptionId,
      misconception_title: misconceptionTitle,
      teacher_note: item.rationale
    };
  });
}

export function generateGrade4Semester1PublicationSql(): string {
  const inspection = inspectDiagnosticIntegrity({
    content: grade4Semester1Diagnosis,
    setKey: grade4Semester1Diagnosis.manifest.id,
    targetVersion: grade4Semester1Diagnosis.manifest.version
  });
  const gate = inspection.gates?.find(
    (candidate) => candidate.gate === "diagnostic-integrity"
  );
  if (!inspection.valid || !gate?.enforced || !gate.valid) {
    throw new Error("Grade 4 semester 1 diagnostic integrity gate did not pass.");
  }

  const publishedContent = structuredClone(grade4Semester1Diagnosis);
  publishedContent.manifest.status = "published";
  publishedContent.manifest.checksum = "";
  const notes = buildTeacherNotes();
  const expectedWrongChoices = publishedContent.judgments.reduce(
    (count, judgment) =>
      count + judgment.choices.filter((choice) => !choice.correct).length,
    0
  );
  if (notes.length !== expectedWrongChoices || notes.length !== 132) {
    throw new Error(
      `Teacher note coverage mismatch: ${notes.length}/${expectedWrongChoices}`
    );
  }

  return `-- Generated by tools/emit-published-set-sql.ts. Do not edit by hand.
-- Rollback:
-- 1. Archive assignments that reference grade4-semester1@1.3.0.
-- 2. Drop diagnosis_distractor_notes after dependent teacher views are removed.
-- 3. Published diagnosis rows are immutable; rollback requires a reviewed forward migration.

create table public.diagnosis_distractor_notes (
  set_key text not null,
  version text not null,
  judgment_id text not null,
  choice_id text not null,
  signal_ids text[] not null check (cardinality(signal_ids) > 0),
  misconception_key text not null check (char_length(trim(misconception_key)) > 0),
  misconception_title text not null check (char_length(trim(misconception_title)) > 0),
  teacher_note text not null check (char_length(trim(teacher_note)) > 0),
  created_at timestamptz not null default now(),
  primary key (set_key, version, judgment_id, choice_id),
  foreign key (set_key, version)
    references public.diagnosis_sets(set_key, version)
    on delete restrict
);

comment on table public.diagnosis_distractor_notes is
  '정확한 발행 버전과 오답 선택에 연결된 교사 전용 해석. 학생·학부모 런타임에는 노출하지 않는다.';

alter table public.diagnosis_distractor_notes enable row level security;

create policy teacher_and_content_team_distractor_note_read
on public.diagnosis_distractor_notes
for select to authenticated
using (
  exists (
    select 1
    from public.teachers teacher
    where teacher.id = auth.uid()
  )
  or public.is_content_team_member()
);

grant select on public.diagnosis_distractor_notes to authenticated;
revoke all on public.diagnosis_distractor_notes from anon;
revoke insert, update, delete, truncate
  on public.diagnosis_distractor_notes
  from authenticated;

create or replace function public.protect_diagnosis_distractor_note()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'published diagnosis distractor notes are immutable';
end;
$$;

create trigger diagnosis_distractor_notes_immutable
before update or delete on public.diagnosis_distractor_notes
for each row execute function public.protect_diagnosis_distractor_note();

create or replace function public.assert_distractor_note_coverage(
  p_set_key text,
  p_version text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  diagnosis_content jsonb;
  expected_count integer;
  actual_count integer;
begin
  select content
  into diagnosis_content
  from public.diagnosis_sets
  where set_key = p_set_key
    and version = p_version;

  if diagnosis_content is null then
    raise exception 'published diagnosis set % at % was not found',
      p_set_key, p_version;
  end if;

  select count(*)
  into expected_count
  from jsonb_array_elements(diagnosis_content -> 'judgments') judgment,
       jsonb_array_elements(judgment -> 'choices') choice
  where not (choice ->> 'correct')::boolean;

  select count(*)
  into actual_count
  from public.diagnosis_distractor_notes note
  where note.set_key = p_set_key
    and note.version = p_version;

  if actual_count <> expected_count then
    raise exception 'distractor note count mismatch: expected %, found %',
      expected_count, actual_count;
  end if;

  if exists (
    select 1
    from jsonb_array_elements(diagnosis_content -> 'judgments') judgment,
         jsonb_array_elements(judgment -> 'choices') choice
    where not (choice ->> 'correct')::boolean
      and not exists (
        select 1
        from public.diagnosis_distractor_notes note
        where note.set_key = p_set_key
          and note.version = p_version
          and note.judgment_id = judgment ->> 'id'
          and note.choice_id = choice ->> 'id'
          and note.signal_ids = array(
            select signal_id #>> '{}'
            from jsonb_array_elements(choice -> 'signalIds') signal_id
            order by signal_id #>> '{}'
          )
      )
  ) then
    raise exception 'a non-correct choice is missing its exact teacher note';
  end if;

  if exists (
    select 1
    from public.diagnosis_distractor_notes note
    where note.set_key = p_set_key
      and note.version = p_version
      and not exists (
        select 1
        from jsonb_array_elements(diagnosis_content -> 'judgments') judgment,
             jsonb_array_elements(judgment -> 'choices') choice
        where judgment ->> 'id' = note.judgment_id
          and choice ->> 'id' = note.choice_id
          and not (choice ->> 'correct')::boolean
      )
  ) then
    raise exception 'an extra or correct-choice teacher note was found';
  end if;
end;
$$;

insert into public.diagnosis_sets (
  set_key,
  version,
  checksum,
  status,
  manifest,
  content,
  published_at,
  release_notes,
  validation_report,
  publication_gate
) values (
  '${publishedContent.manifest.id}',
  '${publishedContent.manifest.version}',
  '',
  'published',
  ${sqlJson(publishedContent.manifest, "manifest")},
  ${sqlJson(publishedContent, "content")},
  '2026-07-31T00:00:00.000Z',
  '4학년 1학기 5개 단원 · 27개 학습 단계 · 54개 진단 판단 발행',
  ${sqlJson(inspection, "validation")},
  ${sqlJson(gate, "gate")}
);

insert into public.diagnosis_distractor_notes (
  set_key,
  version,
  judgment_id,
  choice_id,
  signal_ids,
  misconception_key,
  misconception_title,
  teacher_note
)
select
  seed.set_key,
  seed.version,
  seed.judgment_id,
  seed.choice_id,
  seed.signal_ids,
  seed.misconception_key,
  seed.misconception_title,
  seed.teacher_note
from jsonb_to_recordset(${sqlJson(notes, "notes")}) as seed(
  set_key text,
  version text,
  judgment_id text,
  choice_id text,
  signal_ids text[],
  misconception_key text,
  misconception_title text,
  teacher_note text
);

select public.assert_distractor_note_coverage(
  '${publishedContent.manifest.id}',
  '${publishedContent.manifest.version}'
);
`;
}

export function generateGrade4Semester1PublicationV140Sql(): string {
  const inspection = inspectDiagnosticIntegrity({
    content: grade4Semester1Diagnosis,
    setKey: grade4Semester1Diagnosis.manifest.id,
    targetVersion: grade4Semester1Diagnosis.manifest.version
  });
  const gate = inspection.gates?.find(
    (candidate) => candidate.gate === "diagnostic-integrity"
  );
  if (
    grade4Semester1Diagnosis.manifest.version !== "1.4.0"
    || !inspection.valid
    || !gate?.enforced
    || !gate.valid
  ) {
    throw new Error(
      "Grade 4 semester 1 v1.4.0 diagnostic integrity gate did not pass."
    );
  }

  const publishedContent = structuredClone(grade4Semester1Diagnosis);
  publishedContent.manifest.status = "published";
  publishedContent.manifest.checksum = "";
  const newAnchorIds = new Set([
    "[4수01-04]",
    "[4수01-05]",
    "[4수01-07]",
    "[4수01-08]"
  ]);
  const newAnchors = publishedContent.curriculumAnchors.filter((anchor) =>
    newAnchorIds.has(anchor.id)
  );
  const newStages = publishedContent.learnerStages.filter((stage) =>
    stage.unitId === "multiplication-division"
  );
  const newSignals = publishedContent.signals.filter((item) =>
    item.id.startsWith("mul-div.")
  );
  const newJudgments = publishedContent.judgments.filter((item) =>
    item.unitId === "multiplication-division"
  );
  const newNotes = buildTeacherNotes().filter((item) =>
    item.judgment_id.startsWith("g4s1-muldiv-")
  );
  if (
    newAnchors.length !== 4
    || newStages.length !== 6
    || newSignals.length !== 6
    || newJudgments.length !== 12
    || newNotes.length !== 24
  ) {
    throw new Error("Grade 4 semester 1 v1.4.0 append-only delta is incomplete.");
  }

  return `-- Generated by tools/emit-published-set-sql.ts. Do not edit by hand.
-- Rollback:
-- 1. Archive assignments that reference grade4-semester1@1.4.0.
-- 2. Published diagnosis rows and teacher notes are immutable.
-- 3. Roll back with a reviewed forward migration; keep 1.3.0 unchanged.

with previous as (
  select content
  from public.diagnosis_sets
  where set_key = 'grade4-semester1'
    and version = '1.3.0'
    and status = 'published'
),
expanded as (
  select jsonb_set(
    jsonb_set(
      jsonb_set(
        jsonb_set(
          jsonb_set(
            previous.content,
            '{manifest}',
            ${sqlJson(publishedContent.manifest, "manifest")},
            false
          ),
          '{curriculumAnchors}',
          (previous.content -> 'curriculumAnchors') || ${sqlJson(newAnchors, "anchors")},
          false
        ),
        '{learnerStages}',
        (previous.content -> 'learnerStages') || ${sqlJson(newStages, "stages")},
        false
      ),
      '{signals}',
      jsonb_path_query_array(
        previous.content -> 'signals',
        '$[*] ? (@.id != "needs-scaffold" && @.id != "needs-review")'
      )
      || ${sqlJson(newSignals, "signals")}
      || jsonb_path_query_array(
        previous.content -> 'signals',
        '$[*] ? (@.id == "needs-scaffold" || @.id == "needs-review")'
      ),
      false
    ),
    '{judgments}',
    (previous.content -> 'judgments') || ${sqlJson(newJudgments, "judgments")},
    false
  ) as content
  from previous
)
insert into public.diagnosis_sets (
  set_key,
  version,
  checksum,
  status,
  manifest,
  content,
  published_at,
  release_notes,
  publication_gate
)
select
  'grade4-semester1',
  '1.4.0',
  '',
  'published',
  content -> 'manifest',
  content,
  '2026-07-31T09:00:00.000Z',
  '4학년 1학기 6개 단원 · 33개 학습 단계 · 66개 진단 판단 발행',
  ${sqlJson(gate, "gate")}
from expanded;

insert into public.diagnosis_distractor_notes (
  set_key,
  version,
  judgment_id,
  choice_id,
  signal_ids,
  misconception_key,
  misconception_title,
  teacher_note
)
select
  set_key,
  '1.4.0',
  judgment_id,
  choice_id,
  signal_ids,
  misconception_key,
  misconception_title,
  teacher_note
from public.diagnosis_distractor_notes
where set_key = 'grade4-semester1'
  and version = '1.3.0';

insert into public.diagnosis_distractor_notes (
  set_key,
  version,
  judgment_id,
  choice_id,
  signal_ids,
  misconception_key,
  misconception_title,
  teacher_note
)
select
  seed.set_key,
  seed.version,
  seed.judgment_id,
  seed.choice_id,
  seed.signal_ids,
  seed.misconception_key,
  seed.misconception_title,
  seed.teacher_note
from jsonb_to_recordset(${sqlJson(newNotes, "notes")}) as seed(
  set_key text,
  version text,
  judgment_id text,
  choice_id text,
  signal_ids text[],
  misconception_key text,
  misconception_title text,
  teacher_note text
);

select public.assert_distractor_note_coverage(
  'grade4-semester1',
  '1.4.0'
);
`;
}
